login/urls.py
from django.conf.urls import url

from login import views

app_name = 'login'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ajaxlogin/$', views.ajlogin, name='login'),
    url(r'^aj_username_check/', views.username_check, name='username_check'),
    url(r'^aj_register/', views.register, name='register'),
]

mycode/urls.py
from django.views.generic.base import RedirectView

from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^codes/', include('server.urls')),
    url(r'^$', RedirectView.as_view(url='codes/')),
    url(r'^accounts/login/', include('login.urls')),
]

server/urls.py
from django.conf.urls import url, static

from mycode import settings
from server import views

app_name = 'server'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<code_id>[0-9]+)/$', views.code, name='code'),
    url(r'^(?P<code_id>[0-9]+)/upload/$', views.upload, name='upload'),
]

login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

server/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class CodeAdress(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=300)

    def __str__(self):
        return self.name


class StudentCodes(models.Model):
    name = models.CharField(max_length=100)
    file = models.FileField()

    def __str__(self):
        return self.name

server/forms.py
from django import forms


class DocumentModel(forms.Form):
    docfile = forms.FileField(label='select your code')
    name = forms.CharField(max_length=40)

login/views.py
from django.contrib.auth.models import User

from django.contrib.auth import authenticate

from django.http.response import HttpResponse, Http404, JsonResponse

from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'login/index.html', context={})


def ajlogin(request):
    if not request.is_ajax() or request.method != 'POST':
        raise Http404

    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)

    return JsonResponse({'result': True, })


def username_check(request):
    if not request.is_ajax():
        raise Http404

    ret = {'available': False}
    username = request.GET['username']
    if not User.objects.filter(username=username).exists():
        ret['available'] = True
    return JsonResponse(ret)


def register(request):
    if not request.is_ajax() or request.method != "POST":
        raise Http404
    print request.POST
    username = request.POST['username']
    password = request.POST['password']
    confirm = request.POST['confirm']
    if User.objects.filter(username=username).exists():
        return JsonResponse({'error':  True, 'error_message': "user already exists"})
    if len(password) <= 6:
        return JsonResponse({'error': True, 'error_message' : "password should be at least 7 chars"})
    if password != confirm:
        return JsonResponse({'error': True, 'error_message': "passwords don't match"})
    return JsonResponse({
        'error': False,
        'redirect_url': reversed('server:index'),
    })

server/views.py
import json
from django.contrib.auth import logout

from django.contrib.auth.decorators import login_required

from django.core.urlresolvers import reverse

from django.http.response import HttpResponse, HttpResponseRedirect

from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from server import models
from server.forms import DocumentModel
from server.models import CodeAdress


@login_required
def index(request):
    return render(request, 'server/index.html', context={
        'codeadress_list': CodeAdress.objects.all(),
        'user': request.user,
    })


@login_required
def code(request, code_id):
    code_address = get_object_or_404(models.CodeAdress, pk=code_id)
    myfile = open(code_address.address)
    context = {
        'code': myfile.read(),
        'header': code_address.name,
        'form': DocumentModel(),
    }
    return render(request, template_name='server/view.html', context=context)


@login_required
def upload(request, code_id):
    print request.FILES
    if request.method == 'GET':
        return HttpResponseRedirect(reverse('code', args=(code_id,)))
    form = DocumentModel(request.POST, request.FILES)
    #if not form.is_valid():
        #return HttpResponseRedirect(reverse('code', args=(code_id,)))
    return HttpResponse("we are updating")

login/templates/login/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<script type="text/javascript" src="{% static 'jquery.js' %}"></script>
<script src="{% static 'jquery-ui.js' %}"></script>
<div class="login-page">
  <div class="form">
    <form class="register-form" method="post" action="#" id="registerform">
        {% csrf_token %}
        <input type="text" name="username" placeholder="username" id="register_username">
        <input type="password" name="password" placeholder="password" id="register_password">
        <input type="password" name="confirm" placeholder="confirm your password" id="register_confirm">
        <input type="submit" value="create" id="register_submit_button">
        <div class="errornote" id="register_error_message"></div>
      <p class="message" id="switchtologin">Already registered? <a href="#">Sign In</a></p>
    </form>
      <form action="#" method="post" id="loginform">
         {% csrf_token %}
          <input type="text" name="username" id="id_username" placeholder="username">
          <input type="password" name="password" id="id_password" placeholder="password">
          <input type="submit" id="login_submit_button" value="submit">
          <div class="errornote" id="login_error_message"></div>
        <p class="message" id="switchtoregister">Not registered? <a href="#">Create an account</a></p>
    </form>
  </div>
</div>

<script src="{% static 'submit-login.js' %}"></script>

<script src="{% static 'switch.js' %}"></script>
<script src="{% static 'create-register.js' %}"></script>

server/templates/server/index.html
<h2>under maintenance</h2>
<ul>
    {% for codeadress in codeadress_list %}
        <li><a href="{% url 'server:code' forloop.counter %}">{{ codeadress.name }}</a></li>
    {% endfor %}

</ul>

server/templates/server/view.html
<title>
    {{ header }}
</title>
<html>
{% load staticfiles %}
<head>
    <link rel="stylesheet" href="{% static 'styles/shCore.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'styles/shThemeDefault.css' %}" type="text/css">
</head>
<body>
  <pre class='brush:cpp'>
  {{ code }}
  </pre>
  <form action="upload/" method="post">
      {% csrf_token %}
      <p>{{ form.non_field_errors }}</p>
            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>
      <p> your name : </p>{{ form.name }}
      <p><input type="submit" value="submit"></p>
  </form>
  <script src="../../static/scripts/shCore.js"></script>
  <script src="../../static/scripts/shBrushCpp.js"></script>
  <script>
      SyntaxHighlighter.all();
  </script>
</body>
</html>